### ISSUE TITLE
Sprites are not loading in game even though those are displayed in the editor

### ISSUE THREAD

**Issue by SMWW4mp3** [Yoshimaster96/Superstar-Editor-SMW#4]
Sprites are shown in the editor but won't load in game:
![sesmw_1](https://user-images.githubusercontent.com/28955730/91641345-00b7f700-ea24-11ea-8a1d-da215ec1db7c.png)

Even more weird: this doesn't apply to all sprites in the same level:
![sesmw_2](https://user-images.githubusercontent.com/28955730/91641414-7e7c0280-ea24-11ea-852d-e26fc491047f.png)

I could recreate this bug by placing the red koopas on the right first then placing the blue one, the blue one will not spawn:
![sesmw_3](https://user-images.githubusercontent.com/28955730/91641544-648eef80-ea25-11ea-9cec-fcfd22bc17ce.png)

Also a small video showing which sprites in the level won't spawn and which ones do: 
https://www.youtube.com/watch?v=yoRjo-BmA98

Patch file for the level shown in the first two screenshots (in game it's Yoshis Island 1): 
[spritenotloading.zip](https://github.com/Yoshimaster96/Superstar-Editor-SMW/files/5145574/spritenotloading.zip)

**Comment by Yoshimaster96** [comment]
Hm, I'll take a look at it.

**Comment by Yoshimaster96** [comment]
Hm, it seems the issue is caused by the game expecting the sprites to be sorted in order (if a sprite is too far off-screen to the right, it simply terminates the loop instead of continuing with the rest).

There are two solutions to this:

* I could modify the sprite reading code to simply move on to the next sprite instead of exiting (if you want to do this yourself, change the byte at SNES address $02A84D from $FD to $F8).
* I could actually sort the data in-editor when saving/exporting. This shouldn't be too hard to do either.

I'm currently contemplating which one is the best solution, but the cause has been found at least.

**Comment by Yoshimaster96** [comment]
This issue should hopefully have been fixed (you can redownload the editor, though you'll have to move a sprite and resave for the changes to take effect).

**Comment by SMWW4mp3** [comment]
Redownloaded it, moved a sprite, didn't work for me :(
Also I can still break it by placing the later koopas first then the one close to the Player.

I recorded what/how I did do things this time:
https://www.youtube.com/watch?v=DZagAI-c2YE
(2 clips, first one is the bug still working in v1.1.beta.0, second one is the level again and I move the goomba one tile, saved and it didn't work)

Also tried the hex edit, that one works without any issue for me: 
```
;; Patch with asar
org $02A84D
db $F8 ; $FD
```
![grafik](https://user-images.githubusercontent.com/28955730/91896967-ed15c600-ec99-11ea-9de1-4d73c185525b.png)

**Comment by Yoshimaster96** [comment]
Sorry, I updated the 1.0 version (which has since been removed), and not the 1.1 version. Try again.
